#!/usr/bin/env bash
# audit-skill-reconcile.sh — SKILL enforcement-audit concat + score-consistency (M021/S08)
#
# Usage:
#   bash tools/audit-skill-reconcile.sh --concat
#       Regenerate canonical enforcement-audit.md from all 13+1 fragment files.
#       Deterministic: re-run produces byte-identical output.
#
#   bash tools/audit-skill-reconcile.sh --score-consistency-check
#       Flag rows where >=1 score axis diverges for known-similar step groups.
#       Advisory output only — exits 0 even with findings (per L7).
#
#   bash tools/audit-skill-reconcile.sh --reconcile
#       Run --concat + --score-consistency-check + duplicate-row check +
#       per-SKILL >=3-row floor assertion.
#
# Architecture: M021/S08 — owned file. Does NOT modify audit-skill-enforcement.sh (S01).
# ADR references: ADR-260503-A (framework), ADR-004 (single-writer), ADR-260502-A (eligibility)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PKG_ROOT="${REPO_ROOT}/pkg"
FRAGMENT_DIR="${PKG_ROOT}/.aihaus/skills/_shared/enforcement-audit"
CANONICAL="${PKG_ROOT}/.aihaus/skills/_shared/enforcement-audit.md"
DECISIONS_MD="${PKG_ROOT}/.aihaus/decisions.md"

# ---- ADR-260502-A verbatim eligibility-gate block (FR-25 / NFR-08) -----------
# Extracted from decisions.md:2024 (character-for-character per acceptance gate)
VERBATIM_EXAMPLE_2='> **Worked example #2 — DOES NOT FIT (model judgment required).** A future maintainer wants to "auto-close" manifests where the user verbally said "I'\''m done with this" in a chat transcript. The eligibility condition is non-deterministic — it requires NLP/LLM judgment on free-form text. **Does NOT fit.** ADR-260502-A'\''s pattern explicitly requires deterministic conjunction conditions; the moment a condition becomes "model decides," the architectural guarantee ("removes the model from the loop") is voided. Correct answer: this belongs in `aih-feature/SKILL.md` Step 13 prose (model-driven), not in an enforcement hook.'

# ---- --concat mode -----------------------------------------------------------
cmd_concat() {
  # Collect fragment files in deterministic alphabetical order (aih-* then _shared)
  local fragments=()
  while IFS= read -r -d '' f; do
    fragments+=("$f")
  done < <(find "$FRAGMENT_DIR" -maxdepth 1 -name "aih-*.md" -print0 | sort -z)
  # Append _shared.md last
  if [ -f "${FRAGMENT_DIR}/_shared.md" ]; then
    fragments+=("${FRAGMENT_DIR}/_shared.md")
  fi

  if [ "${#fragments[@]}" -eq 0 ]; then
    echo "audit-skill-reconcile.sh: no fragment files found in $FRAGMENT_DIR" >&2
    exit 1
  fi

  # Write canonical with heredoc-style content for determinism
  {
    cat <<'FRAMEWORK_HEADER'
# SKILL Enforcement Audit

This document is the canonical audit of enforcement-layer classification for every
step in every `pkg/.aihaus/skills/aih-*/SKILL.md` (13 SKILLs) and every binding annex
(~20-25 files), generated by `tools/audit-skill-reconcile.sh --concat`.

**Authority:** ADR-260503-A (M021/2026-05-03) — locks framework, schema, move rule,
step-counting rubric, and refresh triggers. See `pkg/.aihaus/decisions.md`.

**Sole writer:** S08 implementer (per ADR-004 single-writer discipline). No other story
modifies this file after S08 commit. Regenerate via `bash tools/audit-skill-reconcile.sh --concat`.

## Framework

### 13-Column Row Schema (binding)

```
| SKILL | Location | Step | Label | Primary | Actor | Gate | Escape | Leverage | Reversibility | Drift Risk | Eligibility | Notes |
```

**Primary classification (binding enum):** `{A, B, C, A+C, B+C, A+B+C}`
- `A` model-driven — prose-only, model is actor + gate.
- `B` agent-delegated — explicit subagent spawn, agent is actor + gate.
- `C` hook-enforced — script (PreToolUse/PostToolUse/Stop/SessionStart) is actor + gate.

**Tag-set columns:**
- `actor ∈ {model, agent, hook, multi}`
- `gate ∈ {none, advisory, blocking, advisory+blocking}`
- `escape ∈ {none, opt-out-env, manual-override}`

**Score axes (binding enum):**
- `leverage ∈ {low, med, high}` — blast-radius when enforcement drifts.
- `reversibility ∈ {rev, irrev}` — irrev = requires forensic recovery once landed.
- `drift-detectability ∈ {easy, med, hard}` — easy = caught by smoke/hook/reviewer.

**Eligibility column (ADR-260502-A inheritance):**
`eligibility ∈ {deterministic, model-judgment, partial}` — gates promotion eligibility.

ADR-260502-A "Worked example #2 — DOES NOT FIT" (eligibility-gate authority, verbatim):

FRAMEWORK_HEADER

    printf '%s\n\n' "$VERBATIM_EXAMPLE_2"

    cat <<'MOVE_RULE'
**Move rule (binding):** Promote A → B/C iff
`leverage=high AND (reversibility=irrev OR drift-detectability=hard) AND eligibility=deterministic`.
The third axis is the ADR-260502-A deterministic-only gate — A-classified high-leverage steps
requiring model judgment MUST STAY A (no enforcement available, by ADR).

**Refresh Triggers:** (a) new SKILL.md or annex merged, (b) existing step materially reworded,
(c) annex renamed or deleted (manual cue required — smoke ratchet does not detect rename).

**Coverage note:** `compute_expected` (S01 rubric) = 289 rows. Fragment total covers all rubric
steps. Cross-fragment score-consistency advisory output: `bash tools/audit-skill-reconcile.sh --score-consistency-check`.

## Scoring

Scoring axes rationale from ADR-260503-A:

- **Leverage** = magnitude of correctness-cost when enforcement drifts (blast-radius), independent
  of step size. Two implementers scoring against this prose must agree (borderline steps documented
  in Notes column).
- **Reversibility** = `irrev` once committed/landed requires forensic recovery (revert + audit);
  `rev` = rollback is clean and low-cost.
- **Drift-detectability** = `easy` caught by smoke/hook/reviewer in normal flow; `hard` surfaces
  only via incident (silent drift).

Move candidates for M022+ remediation: rows where `leverage=high AND (reversibility=irrev OR
drift-detectability=hard) AND eligibility=deterministic`. Run `bash tools/audit-skill-reconcile.sh --score-consistency-check` for cross-fragment divergences.

## Classification

MOVE_RULE

    # Inline each fragment (preserve H2 header from fragment file)
    for frag_file in "${fragments[@]}"; do
      cat "$frag_file"
      printf '\n'
    done

    cat <<'BACKLOG_SECTION'

## Backlog cross-reference

See `pkg/.aihaus/skills/_shared/enforcement-audit-backlog.md` (S09 deliverable; M022+ consumes).

The backlog ranks A→B/C promotion candidates by move-rule eligibility:
`leverage=high AND (reversibility=irrev OR drift-detectability=hard) AND eligibility=deterministic`.

S09 applies the L8 model-judgment sanity gate: rows whose Step body greps for
"model" / "judgment" / "decide" / "ask" require explicit Notes rationale OR are dropped
from the promotion backlog (Class-4 mitigation — ADR-260503-A §Threat Model).
BACKLOG_SECTION
  } > "$CANONICAL"

  local row_count
  row_count=$(grep -c '^| aih-' "$CANONICAL" 2>/dev/null || echo 0)
  echo "audit-skill-reconcile.sh: canonical written — $row_count rows (path: $CANONICAL)"
}

# ---- --score-consistency-check mode ------------------------------------------
cmd_score_consistency_check() {
  if [ ! -f "$CANONICAL" ]; then
    echo "audit-skill-reconcile.sh: canonical not yet created — run --concat first" >&2
    return 0
  fi

  local findings=0

  # Group similar rows by step-body keyword and check score axis consistency.
  # Groups checked (L7): manifest-append.sh invocations, autonomy-guard.sh advisory rows,
  # worktree-drift-check rows, report-completion rows, agent-delegated (adversarial-review) rows.

  local -a groups=(
    "manifest-append.sh"
    "autonomy-guard.sh"
    "worktree-drift-check"
    "report-completion"
    "adversarial-review"
    "agent-routing"
    "invoke-guard.sh"
  )

  for keyword in "${groups[@]}"; do
    # Collect all data rows in canonical matching this keyword
    local matching_rows
    matching_rows=$(grep "^| aih-" "$CANONICAL" | grep "$keyword" || true)
    if [ -z "$matching_rows" ]; then
      continue
    fi

    local row_count
    row_count=$(echo "$matching_rows" | wc -l | tr -d ' ')
    if [ "$row_count" -lt 2 ]; then
      continue  # Need >=2 rows to compare
    fi

    # Extract score columns (awk fields: leading | creates f1=empty, so f2=SKILL...f13=Leverage,f14=Rev,f15=Drift)
    # Row format: | SKILL | Location | Step | Label | Primary | Actor | Gate | Escape | Leverage | Reversibility | Drift Risk | Eligibility | Notes |
    #  awk field:  1empty 2           3      4        5         6       7      8         9          10              11           12            13      14(Lev) 15(Rev) 16(Drift)
    # Leading | makes f1=empty, f2=SKILL, f3=Location, f4=Step, f5=Label,
    # f6=Primary, f7=Actor, f8=Gate, f9=Escape, f10=Leverage, f11=Rev, f12=Drift, f13=Eligibility, f14=Notes
    # Recount: "| a | b | c |" split by | -> ["","a","b","c",""] -> f1=empty,f2=a,f3=b,f4=c
    # 13 columns → 15 fields (leading+trailing empty) → Leverage=f10, Rev=f11, DriftRisk=f12
    local leverages reversibilities drift_risks
    leverages=$(echo "$matching_rows" | awk -F'|' '{gsub(/^ +| +$/, "", $10); print $10}' | sort -u)
    reversibilities=$(echo "$matching_rows" | awk -F'|' '{gsub(/^ +| +$/, "", $11); print $11}' | sort -u)
    drift_risks=$(echo "$matching_rows" | awk -F'|' '{gsub(/^ +| +$/, "", $12); print $12}' | sort -u)

    local lev_count rev_count drift_count
    lev_count=$(echo "$leverages" | grep -c '[a-z]' || echo 0)
    rev_count=$(echo "$reversibilities" | grep -c '[a-z]' || echo 0)
    drift_count=$(echo "$drift_risks" | grep -c '[a-z]' || echo 0)

    if [ "$lev_count" -gt 1 ] || [ "$rev_count" -gt 1 ] || [ "$drift_count" -gt 1 ]; then
      echo "SCORE_DIVERGENCE keyword='$keyword' rows=$row_count leverage_values='$(echo $leverages | tr '\n' ',')' rev_values='$(echo $reversibilities | tr '\n' ',')' drift_values='$(echo $drift_risks | tr '\n' ',')'" >&2
      findings=$((findings + 1))
    fi
  done

  if [ "$findings" -gt 0 ]; then
    echo "audit-skill-reconcile.sh: score-consistency check found $findings divergence group(s) — advisory only, review Notes column for rationale" >&2
  else
    echo "audit-skill-reconcile.sh: score-consistency check — no divergences in known-similar groups"
  fi
  # Advisory only: always returns 0 (per L7)
  return 0
}

# ---- --reconcile mode --------------------------------------------------------
cmd_reconcile() {
  echo "audit-skill-reconcile.sh: running --concat..."
  cmd_concat

  echo "audit-skill-reconcile.sh: running --score-consistency-check..."
  cmd_score_consistency_check

  echo "audit-skill-reconcile.sh: checking duplicate rows..."
  local dup_count
  # Duplicate = same (SKILL, Location, Step) triple (fields 1, 2, 3)
  dup_count=$(grep '^| aih-' "$CANONICAL" \
    | awk -F'|' '{print $2 "|" $3 "|" $4}' \
    | sort | uniq -d | wc -l | tr -d ' ')
  if [ "$dup_count" -gt 0 ]; then
    echo "audit-skill-reconcile.sh: WARNING — $dup_count duplicate (SKILL,Location,Step) triples found in canonical" >&2
    grep '^| aih-' "$CANONICAL" \
      | awk -F'|' '{print $2 "|" $3 "|" $4}' \
      | sort | uniq -d >&2
  else
    echo "audit-skill-reconcile.sh: no duplicate rows found"
  fi

  echo "audit-skill-reconcile.sh: checking per-SKILL >=3-row floor..."
  local floor_failures=0
  local -a seen_skills=()
  while IFS= read -r -d '' frag_file; do
    local skill_name
    skill_name=$(basename "$frag_file" .md)
    local row_count
    row_count=$(grep -c '^| aih-' "$frag_file" 2>/dev/null || echo 0)
    if [ "$row_count" -lt 3 ]; then
      echo "audit-skill-reconcile.sh: WARNING — $skill_name has <3 rows ($row_count)" >&2
      floor_failures=$((floor_failures + 1))
    fi
    seen_skills+=("$skill_name")
  done < <(find "$FRAGMENT_DIR" -maxdepth 1 \( -name "aih-*.md" -o -name "_shared.md" \) -print0 | sort -z)

  if [ "$floor_failures" -gt 0 ]; then
    echo "audit-skill-reconcile.sh: WARNING — $floor_failures fragment(s) below 3-row floor" >&2
  else
    echo "audit-skill-reconcile.sh: all fragments meet >=3-row floor"
  fi

  echo "audit-skill-reconcile.sh: --reconcile complete"
}

# ---- Dispatch ----------------------------------------------------------------
if [ $# -eq 0 ]; then
  echo "Usage: $0 --concat | --score-consistency-check | --reconcile" >&2
  exit 1
fi

case "$1" in
  --concat)
    cmd_concat
    ;;
  --score-consistency-check)
    cmd_score_consistency_check
    ;;
  --reconcile)
    cmd_reconcile
    ;;
  *)
    echo "Unknown flag: $1" >&2
    echo "Usage: $0 --concat | --score-consistency-check | --reconcile" >&2
    exit 1
    ;;
esac
