#!/usr/bin/env bash
# Best-effort operational context discovery for /aih-init.
# Writes a managed block into .aihaus/memory/workflows/environment.md and a
# report under .aihaus/init/. Never reads plaintext secret files.
set -u

TARGET="${PWD}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      TARGET="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: environment-discovery.sh [--target <repo>]"; exit 0 ;;
    *)
      echo "warn: unknown argument ignored: $1" >&2; shift ;;
  esac
done

ROOT="$(cd "$TARGET" 2>/dev/null && pwd)" || {
  echo "error: target not found: $TARGET" >&2
  exit 1
}

AIHAUS_DIR="${ROOT}/.aihaus"
INIT_DIR="${AIHAUS_DIR}/init"
ENV_FILE="${AIHAUS_DIR}/memory/workflows/environment.md"
mkdir -p "${INIT_DIR}" "$(dirname "${ENV_FILE}")" 2>/dev/null || true

if [[ ! -f "${ENV_FILE}" ]]; then
  cat > "${ENV_FILE}" <<'EOF'
# Workflow Environment Memory

Use this file for repository-specific execution environment notes that should
survive across aihaus runs. Do not store plaintext secrets.
EOF
fi

find_rel() {
  local regex="$1"
  find "${ROOT}" \
    \( -path '*/.git' -o -path '*/node_modules' -o -path '*/.aihaus' -o -path '*/.claude' -o -path '*/dist' -o -path '*/build' -o -path '*/.next' -o -path '*/coverage' \) -prune \
    -o -type f -print 2>/dev/null |
    sed "s#^${ROOT}/##" |
    grep -Ei "${regex}" |
    sort -u | head -20 || true
}

join_lines() {
  local data="$1"
  if [[ -z "${data}" ]]; then
    printf '_not detected_\n'
  else
    printf '%s\n' "${data}" | sed 's/^/- /'
  fi
}

ci_files="$(find_rel '(^|/)buildspec\.ya?ml$|^\.github/workflows/|(^|/)\.gitlab-ci\.yml$|(^|/)bitbucket-pipelines\.yml$|(^|/)azure-pipelines\.yml$|^\.circleci/config\.yml$')"
runtime_files="$(find_rel '(^|/)Dockerfile$|(^|/)docker-compose\.ya?ml$|(^|/)Procfile$|(^|/)serverless\.ya?ml$|(^|/)template\.ya?ml$|(^|/)amplify\.yml$|(^|/)fly\.toml$|(^|/)railway\.json$')"
e2e_files="$(find_rel '(^|/)playwright\.config\.|(^|/)cypress\.config\.|(^|/)e2e/|(^|/)tests/e2e/')"
env_examples="$(find_rel '(^|/)\.env\.example$|(^|/)\.env\.sample$|(^|/)env\.example$|\.env\.example$|\.example\.env$')"
package_jsons="$(find_rel '(^|/)package\.json$')"

package_scripts=""
if [[ -n "${package_jsons}" ]]; then
  while IFS= read -r rel; do
    [[ -z "${rel}" ]] && continue
    snippet="$(grep -E '"(dev|start|build|test|test:e2e|e2e|lint|typecheck|deploy)"[[:space:]]*:' "${ROOT}/${rel}" 2>/dev/null | head -12 | sed 's/^[[:space:]]*//')"
    if [[ -n "${snippet}" ]]; then
      package_scripts="${package_scripts}${rel}: ${snippet}"$'\n'
    fi
  done <<< "${package_jsons}"
fi

codebuild_hint="_not detected_"
if printf '%s\n' "${ci_files}" | grep -Eq '(^|/)buildspec\.ya?ml$'; then
  codebuild_hint="buildspec present; CodeBuild project name must be confirmed from AWS/CI settings"
fi

ts="$(date -u +%FT%TZ 2>/dev/null || echo "unknown")"
block_file="${INIT_DIR}/environment-discovery.md"
cat > "${block_file}" <<EOF
<!-- AIHAUS:ENV-DISCOVERY-START -->
## Environment Discovery

Generated by \`/aih-init\` on ${ts}. This is evidence-based scaffolding. Review
and correct it before treating it as policy. No plaintext secrets were read.

### Runtime Evidence

$(join_lines "${runtime_files}")

### CI/CD Evidence

$(join_lines "${ci_files}")

### CodeBuild

- ${codebuild_hint}

### Credential and Environment Files

$(join_lines "${env_examples}")

### Browser and E2E Evidence

$(join_lines "${e2e_files}")

### Package Scripts

$(join_lines "${package_scripts}")

### Gaps to Confirm

- Runtime owner and deployment path.
- CodeBuild/project or CI job names, if applicable.
- Dev/staging URLs used for Playwright or smoke checks.
- Location of authorized test credentials, without storing secrets here.
- Business protocols that affect validation or release gates.
- Which environments are **online** (staging/prod, \`devops\`-only) vs **offline-local**
  (builder/dev/qa). This scopes env instructions by role — see \`.aihaus/workflows/roles.md\`.
- Custom deploy / online-touching commands → add their patterns to
  \`.aihaus/roles/online-actions.conf\` so the role-guard blocks them for non-\`devops\`
  profiles (built-in defaults already cover kubectl/terraform/gh-workflow/fly/vercel/etc.).
<!-- AIHAUS:ENV-DISCOVERY-END -->
EOF

tmp="${ENV_FILE}.tmp.$$"
if grep -Fq "AIHAUS:ENV-DISCOVERY-START" "${ENV_FILE}" 2>/dev/null; then
  awk -v start="AIHAUS:ENV-DISCOVERY-START" -v end="AIHAUS:ENV-DISCOVERY-END" -v block="${block_file}" '
    index($0,start) { while ((getline line < block) > 0) print line; skip=1; next }
    skip && index($0,end) { skip=0; next }
    !skip { print }
  ' "${ENV_FILE}" > "${tmp}" && mv "${tmp}" "${ENV_FILE}"
else
  { printf '\n'; cat "${block_file}"; } >> "${ENV_FILE}"
fi
rm -f "${tmp}" 2>/dev/null || true

# Role-scoped online env (S4): devops-only template under memory/local/.
# Holds online (staging/prod) facts that are kept out of builder/dev/qa context.
ONLINE_DIR="${AIHAUS_DIR}/memory/local"
ONLINE_FILE="${ONLINE_DIR}/environment-online.md"
mkdir -p "${ONLINE_DIR}" 2>/dev/null || true
if [[ ! -f "${ONLINE_FILE}" ]]; then
  cat > "${ONLINE_FILE}" <<'EOF_ONLINE'
# Online Environment (devops-scoped, local)

> LOCAL + gitignored. Injected into agent context ONLY for profiles holding the
> `devops` role (context-inject.sh reads .aihaus/.profile). builder/dev/qa never
> receive this file. Store credential LOCATIONS only — never plaintext secrets.

## Staging / Homolog
- URL:
- Deploy command:
- Smoke/validation command:
- Credential location (not the secret):

## Production
- URL:
- Promote command:
- Rollback command:
- Approval/owner:

## Online-action patterns
- Add deploy/online command patterns to `.aihaus/roles/online-actions.conf` so
  role-guard.sh blocks them for non-devops profiles.
EOF_ONLINE
fi

echo "environment discovery written: .aihaus/init/environment-discovery.md"
echo "environment memory updated: .aihaus/memory/workflows/environment.md"
[[ -f "${ONLINE_FILE}" ]] && echo "online env template (devops-scoped): .aihaus/memory/local/environment-online.md"
